[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
music_player = "B4RYieJzdH81NwbNoVkRgfZuYBBNbNPKjhPWZ1NxkDie"

# Add a mapping for devnet (fill PROGRAM_ID after deploy)
[programs.devnet]
music_player = "B4RYieJzdH81NwbNoVkRgfZuYBBNbNPKjhPWZ1NxkDie"

[registry]
url = "https://api.apr.dev"

[provider]

cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p ../../frontend/src/idl && cp target/idl/music_player.json ../../frontend/src/idl/music_player.json"


[workspace]
types = "../../frontend/src/"

[test.validator]
rpc_port = 8080